### ISSUE TITLE
Ratchet use

### ISSUE THREAD

**Issue by Forever1Love** [mbonneau/RatchetHttpPusher#1]
Is the document about    Push Integration in  http://socketo.me/docs/push  valid? I copy the code in my project, but it does not work, you can help me ,make a good example and it can run .

**Comment by mbonneau** [comment]
@Forever1Love - This is a simple example for push using `react/http` instead of `zmq`. It follows along in the same pattern as the `zmq` example that is currently on http://socketo.me.
